spring:

  datasource:
    url: jdbc:postgresql://postgres-syncspace:5432/syncspace
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    redis:
      key-prefix: "syncspace:dev:"
      time-to-live: 3600000

  data:
    redis:
      host: redis-syncspace
      port: 6379
      repositories:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/syncspace_realm/protocol/openid-connect/certs
          issuer-uri: http://localhost/auth/realms/syncspace_realm

server:
  port: 9090
  servlet:
    context-path: /api/v1

youtube:
  api:
    key: "AIzaSyDlYWWdCoOTgS2N4TPT7L4X8URiM2ANghU"